### PR TITLE
Dec2020iac

### PR DESCRIPTION
**Pull request by iatechicken**
DSTU2 resources:
supplydelivery.py
substance.py
subscription.py

### CODE REVIEW

**Comment by nazrulworld** [comment]
Thanks a lot, I will do the merge soon, but do you have more resources to push?

**Comment by iatechicken** [comment]
There's like 13~ ish resources left based on the issue board. I'm planning on doing like 2 or 3 a day, which probably gets us to end of this week. Do you need it faster?

**Comment by nazrulworld** [comment]
> There's like 13~ ish resources left based on the issue board. I'm planning on doing like 2 or 3 a day, which probably gets us to end of this week. Do you need it faster?

It's fully fine, take your time, please 💯

**Comment by nazrulworld** [comment]
https://github.com/nazrulworld/fhir.resources/blob/5.X.X/fhir/resources/DSTU2/questionnaire.py there you will find example of nested group also https://github.com/nazrulworld/fhir.resources/blob/master/fhir/resources/STU3/questionnaire.py

**Comment by iatechicken** [comment]
> https://github.com/nazrulworld/fhir.resources/blob/5.X.X/fhir/resources/DSTU2/questionnaire.py there you will find example of nested group also https://github.com/nazrulworld/fhir.resources/blob/master/fhir/resources/STU3/questionnaire.py

hmm ok, so just copy paste mostly with different title/description, and watch for whether it's a ListType or not. thanks! 

One more low hanging question. For the remaining resources, do you want me to cut a new branch and create a new pull request? or should I keep committing on to this pull request?

**Comment by nazrulworld** [comment]
> > https://github.com/nazrulworld/fhir.resources/blob/5.X.X/fhir/resources/DSTU2/questionnaire.py there you will find example of nested group also https://github.com/nazrulworld/fhir.resources/blob/master/fhir/resources/STU3/questionnaire.py
> 
> hmm ok, so just copy paste mostly with different title/description, and watch for whether it's a ListType or not. thanks!
> 
> One more low hanging question. For the remaining resources, do you want me to cut a new branch and create a new pull request? or should I keep committing on to this pull request?

keep committing 👍

**Comment by iatechicken** [comment]
supplydelivery.py
substance.py
subscription.py
searchparameter.py
riskassessment.py
referralrequest.py
questionnaire.py
questionnaireresponse.py
provenance.py
processresponse.py
processrequest.py
parameters.py
paymentreconciliation.py
paymentnotice.py
operationdefinition.py
nutritionorder.py
testscript.py

done

**Comment by nazrulworld** [comment]
Great thanks, 🙏  I will review it soon.
Hope we will have the final release before Christmas vacation.

**Comment by nazrulworld** [comment]
LGTM! Thanks a lot,

**Pull request merged**
