### PR TITLE
R4B

### PR DESCRIPTION
**Pull request by bwalsh**
This PR addresses #110:
* moves fhir/resources to fhir/resources/R4
* creates R4B classes and tests

Currently, testing shows these validation errors:

```# failures
fhir/resources/tests/test_activitydefinition.py - timingTiming null not allowed
fhir/resources/tests/test_implementationguide.py - url missing scheme
fhir/resources/tests/test_library.py -  url missing scheme
fhir/resources/tests/test_plandefinition.py - timingTiming null not allowed, url missing scheme
fhir/resources/tests/test_relatedperson.py -  url missing scheme

 
fhir/resources/tests/test_searchparameter.py - __root__ -> base field required, id ensure this value has at most 64 characters
tests/test_utils_xml.py -  Value is expected from the instance of <class 'fhir.resources.fhirprimitiveextension.FHIRPrimitiveExtension'>, but got type <class 'fhir.resources.R4.fhirprimitiveextension.FHIRPrimitiveExtension'> (type=value_error)

```

TODO: As far as I can tell, these errors are expected - given the example data. 
I wonder if the example data needs to be tweaked in order to generate passing tests?

Please let me know if this is the right approach, feedback ,etc.   
Motivated to get a R4B compatible  and eventually 5.0 releases created.

### CODE REVIEW

**Comment by bwalsh** [comment]
> TODO: As far as I can tell, these errors are expected - given the example data. 
I wonder if the example data needs to be tweaked in order to generate passing tests?

**Comment by nazrulworld** [comment]
Hi @bwalsh thanks a lot for your PR. 
1. It is very important that all tests should pass through travis.
2. I think we will not create a separate folder (sub-package) for R4, there is no major difference between R4 and R4B as far as I understand.

**Comment by nazrulworld** [comment]
https://github.com/nazrulworld/fhir.resources/commit/98b19ecbaa3778fd5ece74990bdc77fd5d1afc70

**Comment by bwalsh** [comment]
@nazrulworld  Hey!  You beat me to it.  Thanks very much.

**Comment by bwalsh** [comment]
@nazrulworld thanks again, are you going to release it on pypi?

**Comment by nazrulworld** [comment]
I hope that within the new year.

**Pull request closed without merging**
