### PR TITLE
Dstu2 more tests

### PR DESCRIPTION
**Pull request by ItayGoren**

### CODE REVIEW

**Comment by ItayGoren** [comment]
@nazrulworld i added tests from the download files to DSTU2. I found couple of bugs in different resources and fixed them.

**Comment by nazrulworld** [comment]
Wow @ItayGoren that is a really great job, thank you so much.

**Comment by ItayGoren** [comment]
@nazrulworld 
i added more tests and pushed them to this branch as well
i have a problem with specimen, i will add it to another branch and open an issue about it
would like you to take a look on what im missing

**Comment by nazrulworld** [comment]
@ItayGoren can you please try to run `isort fhir/resourecs/DSTU2` and `black fhir/resourecs/DSTU2`

**Pull request merged**
