### PR TITLE
Fix #101 ElementDefinition.id typing is incorrect also on R4B package

### LINKED ISSUE #101: ElementDefinition.id typing is incorrect
* fhir.resources version: current
* Python version: 3.7
* Operating System: Mac OS Monterey ver 12.12.1

### Description

The StructureDefinition model generates validation errors for the element.id elements due to the regex defined in the model.  The regex is based on the FHIR id datatype.  However, the element.id element is a string datatype and should not use the id datatype regex.

See the element definition here http://hl7.org/fhir/element.html#Element, and  Element.id  definition here :  http://hl7.org/fhir/elementdefinition.html#id

### What I Did

```
from fhir.resources.structuredefinition import StructureDefinition
for i in us_core_files:
    #print(i.name)
    constraints = {}
    #sd_dict = loads(i.read_text())
    sd = StructureDefinition.parse_file(i)
    


---------------------------------------------------------------------------
ValidationError                           Traceback (most recent call last)
Input In [30], in <cell line: 2>()
      4 constraints = {}
      5 #sd_dict = loads(i.read_text())
----> 6 sd = StructureDefinition.parse_file(i)
      7 #print(sd_dict['type'])
      9 if sd.type =="Observation":

File ~/.pyenv/versions/3.10.2/envs/jupyter/lib/python3.10/site-packages/fhir/resources/fhirabstractmodel.py:243, in FHIRAbstractModel.parse_file(cls, path, content_type, encoding, proto, allow_pickle, **extra)
    233 extra.update({"cls": cls})
    234 obj = load_file(
    235     path,
    236     proto=proto,
   (...)
    241     **extra,
    242 )
--> 243 return cls.parse_obj(obj)

File ~/.pyenv/versions/3.10.2/envs/jupyter/lib/python3.10/site-packages/pydantic/main.py:511, in pydantic.main.BaseModel.parse_obj()

File ~/.pyenv/versions/3.10.2/envs/jupyter/lib/python3.10/site-packages/fhir/resources/fhirabstractmodel.py:105, in FHIRAbstractModel.__init__(__pydantic_self__, **data)
    102 if errors:
    103     raise ValidationError(errors, __pydantic_self__.__class__)
--> 105 BaseModel.__init__(__pydantic_self__, **data)

File ~/.pyenv/versions/3.10.2/envs/jupyter/lib/python3.10/site-packages/pydantic/main.py:331, in pydantic.main.BaseModel.__init__()

ValidationError: 23 validation errors for StructureDefinition
snapshot -> element -> 14 -> id
  string does not match regex "^[A-Za-z0-9\-.]+$" (type=value_error.str.regex; pattern=^[A-Za-z0-9\-.]+$)
snapshot -> element -> 15 -> id
  string does not match regex "^[A-Za-z0-9\-.]+$" (type=value_error.str.regex; pattern=^[A-Za-z0-9\-.]+$)
snapshot -> element -> 16 -> id
  string does not match regex "^[A-Za-z0-9\-.]+$" (type=value_error.str.regex; pattern=^[A-Za-z0-9\-.]+$)
snapshot -> element -> 17 -> id
  string does not match regex "^[A-Za-z0-9\-.]+$" (type=value_error.str.regex; pattern=^[A-Za-z0-9\-.]+$)
snapshot -> element -> 18 -> id
  string does not match regex "^[A-Za-z0-9\-.]+$" (type=value_error.str.regex; pattern=^[A-Za-z0-9\-.]+$)
snapshot -> element -> 19 -> id
  string does not match regex "^[A-Za-z0-9\-.]+$" (type=value_error.str.regex; pattern=^[A-Za-z0-9\-.]+$)
snapshot -> element -> 20 -> id
  string does not match regex "^[A-Za-z0-9\-.]+$" (type=value_error.str.regex; pattern=^[A-Za-z0-9\-.]+$)
snapshot -> element -> 21 -> id
  string does not match regex "^[A-Za-z0-9\-.]+$" (type=value_error.str.regex; pattern=^[A-Za-z0-9\-.]+$)
snapshot -> element -> 22 -> id
  string does not match regex "^[A-Za-z0-9\-.]+$" (type=value_error.str.regex; pattern=^[A-Za-z0-9\-.]+$)
snapshot -> element -> 23 -> id
  string does not match regex "^[A-Za-z0-9\-.]+$" (type=value_error.str.regex; pattern=^[A-Za-z0-9\-.]+$)
snapshot -> element -> 24 -> id
  string does not match regex "^[A-Za-z0-9\-.]+$" (type=value_error.str.regex; pattern=^[A-Za-z0-9\-.]+$)
snapshot -> element -> 25 -> id
  string does not match regex "^[A-Za-z0-9\-.]+$" (type=value_error.str.regex; pattern=^[A-Za-z0-9\-.]+$)
snapshot -> element -> 30 -> id
  string does not match regex "^[A-Za-z0-9\-.]+$" (type=value_error.str.regex; pattern=^[A-Za-z0-9\-.]+$)
snapshot -> element -> 33 -> id
  string does not match regex "^[A-Za-z0-9\-.]+$" (type=value_error.str.regex; pattern=^[A-Za-z0-9\-.]+$)
snapshot -> element -> 34 -> id
  string does not match regex "^[A-Za-z0-9\-.]+$" (type=value_error.str.regex; pattern=^[A-Za-z0-9\-.]+$)
snapshot -> element -> 35 -> id
  string does not match regex "^[A-Za-z0-9\-.]+$" (type=value_error.str.regex; pattern=^[A-Za-z0-9\-.]+$)
snapshot -> element -> 36 -> id
  string does not match regex "^[A-Za-z0-9\-.]+$" (type=value_error.str.regex; pattern=^[A-Za-z0-9\-.]+$)
snapshot -> element -> 37 -> id
  string does not match regex "^[A-Za-z0-9\-.]+$" (type=value_error.str.regex; pattern=^[A-Za-z0-9\-.]+$)
snapshot -> element -> 38 -> id
  string does not match regex "^[A-Za-z0-9\-.]+$" (type=value_error.str.regex; pattern=^[A-Za-z0-9\-.]+$)
snapshot -> element -> 39 -> id
  string does not match regex "^[A-Za-z0-9\-.]+$" (type=value_error.str.regex; pattern=^[A-Za-z0-9\-.]+$)
snapshot -> element -> 40 -> id
  string does not match regex "^[A-Za-z0-9\-.]+$" (type=value_error.str.regex; pattern=^[A-Za-z0-9\-.]+$)
snapshot -> element -> 41 -> id
  string does not match regex "^[A-Za-z0-9\-.]+$" (type=value_error.str.regex; pattern=^[A-Za-z0-9\-.]+$)
snapshot -> element -> 66 -> id
  string does not match regex "^[A-Za-z0-9\-.]+$" (type=value_error.str.regex; pattern=^[A-Za-z0-9\-.]+$)
```

### PR DESCRIPTION
**Pull request by kupsum**
This add fix in https://github.com/nazrulworld/fhir.resources/issues/101 also R4B package.

### CODE REVIEW

**Comment by nazrulworld** [comment]
Hi @kupsum 
First of all thanks a lot for your PR. I can't accept this PR for now, because I am little bit confused about the correct ``Element.id`` type.
According to FHIR specification, bellow is the definition of the property ´id´
```
{'id': 'Element.id',
 'isModifier': False,
 'isSummary': False,
 'mapping': [{'identity': 'rim', 'map': 'n/a'}],
 'max': '1',
 'min': 0,
 'path': 'Element.id',
 'representation': ['xmlAttr'],
 'short': 'Unique id for inter-element referencing',
 'type': [{'code': 'http://hl7.org/fhirpath/System.String',
           'extension': [{'url': 'http://hl7.org/fhir/StructureDefinition/structuredefinition-fhir-type',
                          'valueUrl': 'id'}]}]}
 
```
You can see that an extension 'https://hl7.org/fhir/extensions/StructureDefinition-structuredefinition-fhir-type.html' is used, which clearly indicates that value type should be FHIR primitive type ´id´.

But still you can confirm me about the correct type, I am happy to accept this PR. Happy coding!

NB: it is possible ask relevant question here https://chat.fhir.org

**Comment by kupsum** [comment]
Hi @nazruworld!

I'm referencing [this document about Element](http://hl7.org/fhir/types-definitions.html#Element) in this PR which states `id` as string.

<html>
<body>


Element.id
--
Definition | Unique id for the element within a resource (for internal references). This may be any string value that does not contain spaces.
Short Display | Unique id for inter-element referencing
Cardinality | 0..1
Type | string


</body>
</html>

Also, the R5 codebase already has this `Element.id` specified as `fhirtypes.String`. See https://github.com/nazrulworld/fhir.resources/blob/main/fhir/resources/element.py#L43

**Comment by nazrulworld** [comment]
> Hi @nazruworld!
> 
> I'm referencing [this document about Element](http://hl7.org/fhir/types-definitions.html#Element) in this PR which states `id` as string.
> 
> ## Element.id
> Definition | Unique id for the element within a resource (for internal references). This may be any string value that does not contain spaces. Short Display | Unique id for inter-element referencing Cardinality | 0..1 Type | string

The reference you mentioned, is for R5.

**Comment by kupsum** [comment]
Here is [link to R4](https://hl7.org/fhir/R4B/element-definitions.html#Element). The Element.Id is also `string` in R4B.

**Comment by Horstage** [comment]
Fixed in main with #160.
To be fixed in 7.X.X with #165.

Sorry, I didn't see this PR before. This PR would be the original and the other two duplicates.

**Pull request closed without merging**
