### PR TITLE
WIP: Fix cyclical import

### LINKED ISSUE #11: backboneelement introduced cyclical import as of 8fe3dbcd
* fhir.resources version: 5.1.1.dev0
* Python version: 3.6.9
* Operating System: MacOS

### Description

In 8fe3dbcd, when Black was used on the code and unified the import statements, the import of `extension` was moved from the bottom of the file to the top. Any code that uses `backboneelement.BackboneElement` (in my case an OperationOutcome) now triggers a cyclical import as can be seen in the attached screenshot. Briefly:

- `backboneelement` imports `extension`
- `extension` imports `annotation`
- `annotation` imports `fhirreference`
- `fhirreference` imports `bundle`
- `bundle` attempts to import `backboneelement`, which technically succeeds, but since the first import of `backboneelement` hasn't completed, the `BackboneElement` class isn't available and the import in `bundle` fails.

Expected behavior is for an import of `operationoutcome.OperationOutcome` to succeed.

### What I Did

Text version of the attached image:

```
     from fhir.resources.DSTU2.operationoutcome import OperationOutcome
   File "/home/app/.local/share/virtualenvs/ehr-TNUJx0lF/lib/python3.6/site-packages/fhir/resources/DSTU2/operationoutcome.py", line 8, in <module>
     from . import backboneelement, codeableconcept, domainresource
   File "/home/app/.local/share/virtualenvs/ehr-TNUJx0lF/lib/python3.6/site-packages/fhir/resources/DSTU2/backboneelement.py", line 8, in <module>
     from . import element, extension
   File "/home/app/.local/share/virtualenvs/ehr-TNUJx0lF/lib/python3.6/site-packages/fhir/resources/DSTU2/extension.py", line 8, in <module>
     from . import (address, annotation, attachment, codeableconcept, coding,
   File "/home/app/.local/share/virtualenvs/ehr-TNUJx0lF/lib/python3.6/site-packages/fhir/resources/DSTU2/annotation.py", line 8, in <module>
     from . import element, fhirdate, fhirreference
   File "/home/app/.local/share/virtualenvs/ehr-TNUJx0lF/lib/python3.6/site-packages/fhir/resources/DSTU2/fhirreference.py", line 116, in <module>
     from . import bundle
   File "/home/app/.local/share/virtualenvs/ehr-TNUJx0lF/lib/python3.6/site-packages/fhir/resources/DSTU2/bundle.py", line 64, in <module>
     class BundleEntry(backboneelement.BackboneElement):
 AttributeError: module 'fhir.resources.DSTU2.backboneelement' has no attribute 'BackboneElement'
```

image

### PR DESCRIPTION
**Pull request by mmabey**
Fixes #11 by moving the import statement for `extension` from a global-level import to a local import in the class method that uses it.

Depends on changes made in #10.

### CODE REVIEW

**Comment by nazrulworld** [comment]
@mmabey thank you so much, I will review it soon and do a release.

**Comment by mmabey** [comment]
Per our discussion in #13, I'm going to wait until support for DSTU 2 is added back in before resolving conflicts in this PR.

**Comment by mmabey** [comment]
I finally had some time to look at the refactor you did last week, and it seems the cyclical import issue is no longer present, so I'm closing the PR.

**Comment by nazrulworld** [comment]
@mmabey Thank you so much for your valuable contributions, I have merged in 5.X.X branch.
Added your name here https://github.com/nazrulworld/fhir.resources/blob/5.X.X/AUTHORS.rst
Let me know if it is correct and also you can add your email address here if you want.

**Comment by mmabey** [comment]
@nazrulworld Thank you. Yes my name is correct as you have it. I don't really want my email address included, but could you include my GitHub username instead? Thanks!

**Pull request closed without merging**
